// PDF generation utility — creates a PDF blob from report text using html2pdf.js

let _loaded = false;
async function ensureLib() {
  if (_loaded || window.html2pdf) { _loaded = true; return; }
  await new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
    s.onload = () => { _loaded = true; resolve(); };
    s.onerror = reject;
    document.head.appendChild(s);
  });
}

function buildReportHTML(reportText, reportType, childInfo, specialistInfo) {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Convert plain text with UPPERCASE headers to styled HTML
  const bodyHtml = (reportText || '').split('\n').map(line => {
    const t = line.trim();
    if (!t) return '<br>';
    // Detect section headers (UPPERCASE lines or Hebrew section-like lines)
    if (/^[A-Z\s\/&:]{4,}$/.test(t) || /^[A-Z\s\/&:].*:$/.test(t)) {
      return '<h3 style="margin:16px 0 6px;font-size:12pt;font-weight:700;color:#0d9488;border-bottom:1px solid #e8f4f2;padding-bottom:3px;">' + t + '</h3>';
    }
    return '<p style="margin:0 0 3px;font-size:10.5pt;line-height:1.6;color:#1e293b;">' + t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;') + '</p>';
  }).join('');

  return `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;max-width:700px;padding:10px;">
    <div style="text-align:center;margin-bottom:18px;padding-bottom:12px;border-bottom:2px solid #0d9488;">
      <div style="font-size:16pt;font-weight:700;color:#0d9488;margin-bottom:2px;">Huddledin</div>
      <div style="font-size:12pt;font-weight:600;color:#1e293b;">${(reportType || 'Clinical Report').replace(/</g,'&lt;')}</div>
    </div>
    <table style="width:100%;font-size:9pt;color:#475569;margin-bottom:14px;border-collapse:collapse;">
      <tr><td style="padding:2px 8px 2px 0;"><b>Patient:</b> ${(childInfo?.name||'—').replace(/</g,'&lt;')}</td><td><b>DOB:</b> ${childInfo?.dob||'—'}</td></tr>
      <tr><td style="padding:2px 8px 2px 0;"><b>Age:</b> ${childInfo?.age||'—'}</td><td><b>Date:</b> ${date}</td></tr>
      <tr><td style="padding:2px 8px 2px 0;"><b>Specialist:</b> ${(specialistInfo?.name||'—').replace(/</g,'&lt;')}${specialistInfo?.credentials?', '+specialistInfo.credentials:''}</td><td><b>Specialty:</b> ${(specialistInfo?.specialty||'—').replace(/</g,'&lt;')}</td></tr>
    </table>
    ${bodyHtml}
    <div style="margin-top:28px;padding-top:10px;border-top:1px solid #e8f4f2;font-size:8pt;color:#94a3b8;text-align:center;">
      Generated by Huddledin · ${date} · Confidential
    </div>
  </div>`;
}

// Generate PDF as Blob (for uploading to storage)
export async function generatePDFBlob(reportText, reportType, childInfo, specialistInfo) {
  await ensureLib();
  const html = buildReportHTML(reportText, reportType, childInfo, specialistInfo);

  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = html;
  tempDiv.style.cssText = 'position:fixed;top:0;left:0;width:210mm;z-index:-9999;opacity:0;pointer-events:none;';
  document.body.appendChild(tempDiv);

  // Wait for browser to layout
  await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));

  try {
    const blob = await window.html2pdf().set({
      margin: [15, 15, 15, 15],
      html2canvas: { scale: 2, useCORS: true, logging: false },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    }).from(tempDiv).outputPdf('blob');
    return blob;
  } finally {
    document.body.removeChild(tempDiv);
  }
}
