// PDF Export — generates downloadable PDF from report text

let _html2pdfLoaded = false;

async function ensureHtml2Pdf() {
  if (_html2pdfLoaded || window.html2pdf) { _html2pdfLoaded = true; return; }
  await new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
    script.onload = () => { _html2pdfLoaded = true; resolve(); };
    script.onerror = reject;
    document.head.appendChild(script);
  });
}

function buildReportHTML(reportData, generatedText, childInfo, specialistInfo) {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  // Convert plain text with UPPERCASE headers to styled HTML
  const bodyHtml = (generatedText || '').split('\n').map(line => {
    const trimmed = line.trim();
    if (!trimmed) return '<br>';
    if (/^[A-Z\s\/&]{4,}$/.test(trimmed) || /^[\u0590-\u05FF\s\/&]{3,}:?$/.test(trimmed)) {
      return `<h3 style="margin:18px 0 6px;font-size:13px;font-weight:700;color:#0d9488;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #e8f4f2;padding-bottom:4px;">${trimmed}</h3>`;
    }
    return `<p style="margin:0 0 4px;font-size:11px;line-height:1.6;color:#1e293b;">${trimmed}</p>`;
  }).join('');

  return `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;max-width:700px;padding:20px;">
      <div style="text-align:center;margin-bottom:20px;padding-bottom:14px;border-bottom:2px solid #0d9488;">
        <div style="font-size:18px;font-weight:700;color:#0d9488;margin-bottom:2px;">Huddledin</div>
        <div style="font-size:14px;font-weight:600;color:#1e293b;">${reportData.report_type || 'Clinical Report'}</div>
      </div>
      <table style="width:100%;font-size:10px;color:#475569;margin-bottom:16px;border-collapse:collapse;">
        <tr><td style="padding:2px 8px 2px 0;"><b>Patient:</b> ${childInfo?.name || '—'}</td><td><b>DOB:</b> ${childInfo?.dob || '—'}</td></tr>
        <tr><td style="padding:2px 8px 2px 0;"><b>Age:</b> ${childInfo?.age || '—'}</td><td><b>Date:</b> ${date}</td></tr>
        <tr><td style="padding:2px 8px 2px 0;"><b>Specialist:</b> ${specialistInfo?.name || '—'}${specialistInfo?.credentials ? ', ' + specialistInfo.credentials : ''}</td><td><b>Specialty:</b> ${specialistInfo?.specialty || '—'}</td></tr>
      </table>
      ${bodyHtml}
      <div style="margin-top:30px;padding-top:12px;border-top:1px solid #e8f4f2;font-size:9px;color:#94a3b8;text-align:center;">
        Generated by Huddledin · ${date} · Confidential
      </div>
    </div>
  `;
}

export async function downloadReportPDF(reportData, generatedText, childInfo, specialistInfo) {
  await ensureHtml2Pdf();
  const html = buildReportHTML(reportData, generatedText, childInfo, specialistInfo);
  const filename = `${(reportData.report_type || 'report').replace(/\s/g, '_')}_${(childInfo?.name || 'patient').replace(/\s/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;

  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = html;
  tempDiv.style.cssText = 'position:absolute;left:-9999px;width:210mm;';
  document.body.appendChild(tempDiv);

  try {
    await window.html2pdf().set({
      margin: [15, 15, 15, 15],
      filename,
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    }).from(tempDiv).save();
  } finally {
    document.body.removeChild(tempDiv);
  }
}

export { buildReportHTML };
