// PDF generation using jsPDF — direct text rendering, no HTML conversion needed

let _loaded = false;
async function ensureLib() {
  if (_loaded || window.jspdf) { _loaded = true; return; }
  await new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
    s.onload = () => { _loaded = true; resolve(); };
    s.onerror = reject;
    document.head.appendChild(s);
  });
}

export async function generatePDFBlob(reportText, reportType, childInfo, specialistInfo) {
  await ensureLib();
  const { jsPDF } = window.jspdf;
  if (!jsPDF) throw new Error('PDF library failed to load');

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginL = 20, marginR = 20, marginT = 20, marginB = 20;
  const contentW = pageW - marginL - marginR;
  let y = marginT;

  const addPage = () => { doc.addPage(); y = marginT; };
  const checkSpace = (needed) => { if (y + needed > pageH - marginB) addPage(); };

  // ── Header ──
  doc.setFontSize(18);
  doc.setTextColor(13, 148, 136); // teal
  doc.text('Huddledin', pageW / 2, y, { align: 'center' });
  y += 8;
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 59);
  doc.text(reportType || 'Clinical Report', pageW / 2, y, { align: 'center' });
  y += 6;
  doc.setDrawColor(13, 148, 136);
  doc.setLineWidth(0.5);
  doc.line(marginL, y, pageW - marginR, y);
  y += 8;

  // ── Patient info table ──
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const infoLines = [
    ['Patient: ' + (childInfo?.name || '—'), 'DOB: ' + (childInfo?.dob || '—')],
    ['Age: ' + (childInfo?.age || '—'), 'Date: ' + date],
    ['Specialist: ' + (specialistInfo?.name || '—') + (specialistInfo?.credentials ? ', ' + specialistInfo.credentials : ''), 'Specialty: ' + (specialistInfo?.specialty || '—')],
  ];
  infoLines.forEach(([left, right]) => {
    doc.text(left, marginL, y);
    doc.text(right, pageW / 2 + 5, y);
    y += 5;
  });
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  doc.line(marginL, y, pageW - marginR, y);
  y += 6;

  // ── Report body ──
  const lines = (reportText || '').split('\n');
  lines.forEach(line => {
    const trimmed = line.trim();
    if (!trimmed) { y += 3; return; }

    // Detect section headers (UPPERCASE or ending with colon after uppercase)
    const isHeader = /^[A-Z][A-Z\s\/&:]+:?\s*$/.test(trimmed) || /^[A-Z\s\/&]{4,}$/.test(trimmed);

    if (isHeader) {
      checkSpace(12);
      y += 4;
      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(13, 148, 136);
      doc.text(trimmed, marginL, y);
      y += 5;
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.1);
      doc.line(marginL, y, pageW - marginR, y);
      y += 4;
    } else {
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(30, 41, 59);
      // Word-wrap long lines
      const wrapped = doc.splitTextToSize(trimmed, contentW);
      wrapped.forEach(wl => {
        checkSpace(5);
        doc.text(wl, marginL, y);
        y += 4.5;
      });
      y += 1;
    }
  });

  // ── Footer ──
  checkSpace(15);
  y += 6;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  doc.line(marginL, y, pageW - marginR, y);
  y += 5;
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Huddledin · ' + date + ' · Confidential', pageW / 2, y, { align: 'center' });

  // Add page numbers
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text('Page ' + i + ' of ' + totalPages, pageW - marginR, pageH - 10, { align: 'right' });
  }

  const blob = doc.output('blob');
  console.log('[pdf] Generated:', blob.size, 'bytes,', totalPages, 'pages');
  return blob;
}
